Repository qrtl/axls-oca, pull requests merged in 2022-12, with the labels that each got.

#8 [3033][ADD] web_environment_ribbon
  setup/web_environment_ribbon/odoo/addons/web_environment_ribbon
  setup/web_environment_ribbon/setup.py
  web_environment_ribbon/README.rst
  web_environment_ribbon/__init__.py
  web_environment_ribbon/__manifest__.py
  web_environment_ribbon/data/ribbon_data.xml
  web_environment_ribbon/i18n/ca.po
  web_environment_ribbon/i18n/de.po
  web_environment_ribbon/i18n/es.po
  web_environment_ribbon/i18n/fr.po
  web_environment_ribbon/i18n/hr.po
  web_environment_ribbon/i18n/nl.po
  web_environment_ribbon/i18n/nl_NL.po
  web_environment_ribbon/i18n/pt.po
  web_environment_ribbon/i18n/pt_BR.po
  web_environment_ribbon/i18n/sl.po
  web_environment_ribbon/i18n/zh.po
  web_environment_ribbon/i18n/zh_CN.po
  web_environment_ribbon/models/__init__.py
  web_environment_ribbon/models/web_environment_ribbon_backend.py
  web_environment_ribbon/readme/CONFIGURE.rst
  web_environment_ribbon/readme/CONTRIBUTORS.rst
  web_environment_ribbon/readme/DESCRIPTION.rst
  web_environment_ribbon/readme/USAGE.rst
  web_environment_ribbon/static/description/icon.png
  web_environment_ribbon/static/description/index.html
  web_environment_ribbon/static/description/screenshot.png
  web_environment_ribbon/static/src/css/ribbon.css
  web_environment_ribbon/static/src/js/ribbon.js
  web_environment_ribbon/tests/__init__.py
  web_environment_ribbon/tests/test_environment_ribbon_data.py
Labels: staging

#7 [2934][ADD] stock_move_location
  setup/stock_move_location/odoo/addons/stock_move_location
  setup/stock_move_location/setup.py
  stock_move_location/README.rst
  stock_move_location/__init__.py
  stock_move_location/__manifest__.py
  stock_move_location/data/stock_quant_view.xml
  stock_move_location/i18n/de.po
  stock_move_location/i18n/es.po
  stock_move_location/i18n/fr.po
  stock_move_location/i18n/fr_BE.po
  stock_move_location/i18n/fr_FR.po
  stock_move_location/i18n/ja.po
  stock_move_location/i18n/ja_JP.po
  stock_move_location/i18n/stock_move_location.pot
  stock_move_location/init_hook.py
  stock_move_location/models/__init__.py
  stock_move_location/models/stock_move.py
  stock_move_location/models/stock_picking.py
  stock_move_location/models/stock_picking_type.py
  stock_move_location/readme/CONTRIBUTORS.rst
  stock_move_location/readme/DESCRIPTION.rst
  stock_move_location/readme/ROADMAP.rst
  stock_move_location/readme/USAGE.rst
  stock_move_location/security/ir.model.access.csv
  stock_move_location/static/description/icon.png
  stock_move_location/static/description/index.html
  stock_move_location/tests/__init__.py
  stock_move_location/tests/test_common.py
  stock_move_location/tests/test_move_location.py
  stock_move_location/tests/test_stock_fillwithstock.py
  stock_move_location/views/stock_picking.xml
  stock_move_location/views/stock_picking_type_views.xml
  stock_move_location/wizard/__init__.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: good to merge

#12 [3025][ADD] excel_import_export
  excel_import_export/README.rst
  excel_import_export/__init__.py
  excel_import_export/__manifest__.py
  excel_import_export/controllers/__init__.py
  excel_import_export/controllers/report.py
  excel_import_export/i18n/it.po
  excel_import_export/i18n/zh_CN.po
  excel_import_export/models/__init__.py
  excel_import_export/models/common.py
  excel_import_export/models/ir_report.py
  excel_import_export/models/styles.py
  excel_import_export/models/xlsx_export.py
  excel_import_export/models/xlsx_import.py
  excel_import_export/models/xlsx_report.py
  excel_import_export/models/xlsx_template.py
  excel_import_export/readme/CONTRIBUTORS.rst
  excel_import_export/readme/DESCRIPTION.rst
  excel_import_export/readme/INSTALL.rst
  excel_import_export/readme/ROADMAP.rst
  excel_import_export/readme/USAGE.rst
  excel_import_export/security/ir.model.access.csv
  excel_import_export/static/description/common_wizard.png
  excel_import_export/static/description/icon.png
  excel_import_export/static/description/index.html
  excel_import_export/static/description/xlsx_template.png
  excel_import_export/static/src/js/report/action_manager_report.esm.js
  excel_import_export/views/xlsx_report.xml
  excel_import_export/views/xlsx_template_view.xml
  excel_import_export/wizard/__init__.py
  excel_import_export/wizard/export_xlsx_wizard.py
  excel_import_export/wizard/export_xlsx_wizard.xml
  excel_import_export/wizard/import_xlsx_wizard.py
  excel_import_export/wizard/import_xlsx_wizard.xml
  excel_import_export/wizard/report_xlsx_wizard.py
  excel_import_export/wizard/report_xlsx_wizard.xml
  requirements.txt
  setup/excel_import_export/odoo/addons/excel_import_export
  setup/excel_import_export/setup.py
Labels: staging, good to merge

#13 [2934][FIX] stock_move_location: stock_move_location_line_ids
  stock_move_location/__manifest__.py
  stock_move_location/wizard/stock_move_location.py
  stock_move_location/wizard/stock_move_location.xml
  stock_move_location/wizard/stock_move_location_line.py
Labels: staging
